name: Weekly Sync

on:
  schedule:
    - cron: '0 16 * * 0'  # 每周日 16:00 UTC，即北京时间周一凌晨 00:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Sync from upstream repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add upstream https://github.com/bei-ko/bei-ko.github.io.git
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
